"""Export a scene to Pebble C drawing logic.

The handoff to the runtime is an explicit display list, not a raster. This
exporter emits a generated C header containing the scene's ops as a static
array plus a tiny renderer that walks it with the Pebble graphics context.

The generated code is mechanical and easy to regenerate, so commit it only as
an intentional build artifact.
"""

from __future__ import annotations

from pathlib import Path

from .palette import gradient_stops, resolve
from .scene import (
    Bitmap,
    FillRect,
    FramebufferPatch,
    Gradient,
    Line,
    Pdc,
    Scene,
    StrokeRect,
    Text,
)

_HEADER = """\
// Generated by tens.export_c — do not edit by hand.
// Regenerate with: python scripts/export_headers.py
#pragma once
#include <pebble.h>

"""


def _gcolor(scene: Scene, key: str) -> str:
    return resolve(scene.palette_name, scene.dark_mode).gcolor(key)


def _op_to_c(scene: Scene, op) -> str:
    if isinstance(op, FillRect):
        return (
            f"  graphics_context_set_fill_color(ctx, {_gcolor(scene, op.color)});\n"
            f"  graphics_fill_rect(ctx, GRect({op.x}, {op.y}, {op.w}, {op.h}), "
            f"{op.radius}, GCornerNone);"
        )
    if isinstance(op, StrokeRect):
        return (
            f"  graphics_context_set_stroke_color(ctx, {_gcolor(scene, op.color)});\n"
            f"  graphics_draw_rect(ctx, GRect({op.x}, {op.y}, {op.w}, {op.h}));"
        )
    if isinstance(op, Line):
        return (
            f"  graphics_context_set_stroke_color(ctx, {_gcolor(scene, op.color)});\n"
            f"  graphics_context_set_stroke_width(ctx, {op.width});\n"
            f"  graphics_draw_line(ctx, GPoint({op.x1}, {op.y1}), "
            f"GPoint({op.x2}, {op.y2}));"
        )
    if isinstance(op, Text):
        align = {
            "left": "GTextAlignmentLeft",
            "center": "GTextAlignmentCenter",
            "right": "GTextAlignmentRight",
        }.get(op.align, "GTextAlignmentLeft")
        text = op.text.replace("\\", "\\\\").replace('"', '\\"')
        return (
            f"  graphics_context_set_text_color(ctx, {_gcolor(scene, op.color)});\n"
            f"  graphics_draw_text(ctx, \"{text}\", "
            f"fonts_get_system_font(FONT_KEY_{op.font}),\n"
            f"      GRect({op.x}, {op.y}, {op.w}, {op.h}), "
            f"GTextOverflowModeTrailingEllipsis, {align}, NULL);"
        )
    if isinstance(op, Gradient):
        # Snapshot export approximates a gradient with a flat fill of its
        # middle stop. The live watchface (src/c/render.c) does the real
        # per-pixel spectral mapping; this exporter is for static scenes.
        stops = gradient_stops(op.gradient)
        r, g, b = stops[len(stops) // 2]
        return (
            f"  // gradient '{op.gradient}' span={op.span or op.w} "
            f"offset={op.offset} -> flat mid-stop approximation\n"
            f"  graphics_context_set_fill_color(ctx, GColorFromRGB({r}, {g}, {b}));\n"
            f"  graphics_fill_rect(ctx, GRect({op.x}, {op.y}, {op.w}, {op.h}), "
            f"0, GCornerNone);"
        )
    if isinstance(op, (Bitmap, Pdc, FramebufferPatch)):
        return (
            f"  // TODO: resource-backed op '{op.kind}' "
            f"({getattr(op, 'resource', getattr(op, 'data_resource', '?'))}) "
            f"at ({op.x}, {op.y}) — wire up in render.c"
        )
    raise TypeError(f"cannot export op {op!r}")  # pragma: no cover


def scene_to_c(scene: Scene, func_name: str = "tens_render_scene") -> str:
    """Return generated C source rendering ``scene`` via a graphics context."""
    body = "\n".join(_op_to_c(scene, op) for op in scene.ops)
    bg = _gcolor(scene, scene.background)
    return (
        _HEADER
        + f"// canvas {scene.width}x{scene.height}, palette '{scene.palette_name}', "
        + f"{len(scene.ops)} ops\n"
        + f"static void {func_name}(GContext *ctx, GRect bounds) {{\n"
        + f"  graphics_context_set_fill_color(ctx, {bg});\n"
        + "  graphics_fill_rect(ctx, bounds, 0, GCornerNone);\n\n"
        + body
        + "\n}\n"
    )


def export_header(scene: Scene, path: str | Path, func_name: str = "tens_render_scene") -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(scene_to_c(scene, func_name), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    import argparse

    from .preview import _default_scene

    parser = argparse.ArgumentParser(description="Export a Tens scene to C.")
    parser.add_argument(
        "-o", "--out", default="../src/c/scene_generated.h", help="output header path"
    )
    args = parser.parse_args(argv)
    out = export_header(_default_scene(), args.out)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
